schemaVersion: 2.2.0
metadata:
  generateName: ${{values.artifact_id}}
components:
  - name: development-tooling
    container:
#      image: quay.io/devfile/universal-developer-image:ubi8-277c10c
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      env:
        - name: USE_JAVA21
          value: "true"
        - name: KUBEDOCK_ENABLED
          value: "true"
        - name: DOCKER_HOST
          value: "tcp://127.0.0.1:2475"
        - name: TESTCONTAINERS_RYUK_DISABLED
          value: "true"
#         - name: KUBEDOCK_PARAMS
# #          value: "--reverse-proxy --kubeconfig /home/user/.kube/config --initimage quay.io/agiertli/kubedock:0.13.0"
#           value: "--reverse-proxy"
        - name: QUARKUS_HTTP_HOST
          value: 0.0.0.0
        - name: MAVEN_OPTS
          value: "-Dmaven.repo.local=/home/user/.m2/repository"
      memoryLimit: 4Gi
      cpuLimit: 2500m
      volumeMounts:
        - name: m2
          path: /home/user/.m2
{%- if values.verify_commits == 'enabled' %}
        - name: home
          path: /projects/home
{%- endif %}
      endpoints:
        - name: quarkus-dev
          targetPort: 8080
          exposure: public
          secure: false
          protocol: https
        - name: debug
          targetPort: 5005
          exposure: none
          secure: false
          protocol: tcp
        - name: tests
          targetPort: 8081
          exposure: none
          secure: false
          protocol: tcp
  - name: m2
    volume:
      size: 1G
commands:
  - id: enabledevui
    exec:
      label: "0. Enable Quarkus Dev UI"
      component: development-tooling
      commandLine: "export DEVUI_URL=$(oc get dw -o=jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}');sed -i 's/<SOMETHING>/'"$DEVUI_URL"'/g' /projects/hero4/src/main/resources/application.properties;"
      group:
        kind: build
        isDefault: true
  - id: package
    exec:
      label: "1. Package the application"
      component: development-tooling
      commandLine: "./mvnw package"
      group:
        kind: build
        isDefault: true
  
  - id: start-dev
    exec:
      label: "2. Start Development mode (Hot reload + debug)"
      component: development-tooling
      commandLine: "./mvnw compile quarkus:dev"
      group:
        kind: run
        isDefault: true

